# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening this issue. A review of the feedback will come soon. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thank you for the pull request! A review is required before it is merged. In the meantime, please check out the [contributing guidelines](https://docs.github.com/en/contributing).